# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(('Paladin (Ancients)',), 'Paladin (Ancients)'), (('Cleric (Arcana)',), 'Cleric (Arcana)'), (('Warlock (Archfey)',), 'Warlock (Archfey)'), (('Druid (Arctic)',), 'Druid (Arctic)'), (('Artificier',), 'Artificier'), (('Barbarian',), 'Barbarian'), (('Bard',), 'Bard'), (('Cleric',), 'Cleric'), (('Druid (Coast)',), 'Druid (Coast)'), (('Paladin (Crown)',), 'Cleric (Crown)'), (('Cleric (Death)',), 'Cleric (Death)'), (('Druid (Desert)',), 'Druid (Desert)'), (('Paladin (Devotion)',), 'Paladin (Devotion)'), (('Druid',), 'Druid'), (('Fighter (Eldritch Knight)',), 'Fighter (Eldritch Knight)'), (('Warlock (Fiend)',), 'Warlock (Fiend)'), (('Fighter',), 'FIghter'), (('Druid (Forest)',), 'Druid (Forest)'), (('Warlock (Great Old One)',), 'Warlock (Great Old One)'), (('Druid (Grassland)',), 'Druid (Grassland)'), (('Cleric (Nature)',), 'Cleric (Nature)'), (('Cleric (Knowledge)',), 'Cleric (Knowledge)'), (('Cleric (Life)',), 'Cleric (Life)'), (('Cleric (Light)',), 'Cleric (Light)'), (('Paladin (Oathbreaker)',), 'Paladin (Oathbreaker)'), (('Paladin',), 'Paladin'), (('Ranger',), 'Ranger'), (('Rogue',), 'Rogue'), (('Sorcerer',), 'Sorcerer'), (('Cleric (Swamp)',), 'Cleric (Swamp)'), (('Cleric (Tempest)',), 'Cleric (Tempest)'), (('Cleric (Trickery)',), 'Cleric (Trickery)'), (('Rogue (Arcane Trickster)',), 'Rogue (Arcane Trickster)'), (('Druid (Underdark)',), 'Druid (Underdark)'), (('Warlock (Undying Light)',), 'Warlock (Undying)'), (('Paladin (Vengeance)',), 'Paladin (Vengeance)'), (('Cleric (War)',), 'Cleric (War)'), (('Warlock',), 'Warlock'), ('Wizard', 'Wizard')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'Abjuration'), ('C', 'Conjuration'), ('D', 'Divination'), ('E', 'Enchantment'), ('EV', 'Evocation'), ('I', 'Illusion'), ('N', 'Necromancy'), ('T', 'Transmutation')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level', models.IntegerField(default=0)),
                ('casting_time', models.CharField(max_length=200)),
                ('range', models.CharField(max_length=50)),
                ('components', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=3000)),
                ('classes', models.ManyToManyField(to='spells.Class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spells.School')),
            ],
        ),
    ]
