# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level', models.IntegerField(default=0)),
                ('school', models.CharField(choices=[('A', 'Abjuration'), ('C', 'Conjuration'), ('D', 'Divination'), ('E', 'Enchantment'), ('EV', 'Evocation'), ('I', 'Illusion'), ('N', 'Necromancy'), ('T', 'Transmutation')], default='EV', max_length=2)),
                ('casting_time', models.CharField(max_length=200)),
                ('range', models.CharField(max_length=50)),
                ('components', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('classes', models.CharField(max_length=150)),
            ],
        ),
    ]
